export enum Architecture {
  Arm32 = 'arm32',
  Arm64 = 'arm64',
  Bit32 = 'bit32',
  Bit64 = 'bit64',
}

export enum Platform {
  Mac = 'mac',
  Linux = 'linux',
  Windows = 'win',
}

export enum System {
  MacArm32 = 'mac-arm32',
  MacArm64 = 'mac-arm64',
  MacBit32 = 'mac-bit32',
  MacBit64 = 'mac-bit64',
  LinuxArm32 = 'linux-arm32',
  LinuxArm64 = 'linux-arm64',
  LinuxBit32 = 'linux-bit32',
  LinuxBit64 = 'linux-bit64',
  WindowsArm32 = 'win-arm32',
  WindowsArm64 = 'win-arm64',
  WindowsBit32 = 'win-bit32',
  WindowsBit64 = 'win-bit64',
}

export enum License {
  BSDZeroClauseLicense = '0bsd',
  AcademicFreeLicensev3 = 'afl-3.0',
  GNUAfferoGeneralPublicLicensev3 = 'agpl-3.0',
  ApacheLicense2 = 'apache-2.0',
  ArtisticLicense2 = 'artistic-2.0',
  BlueOakModelLicense1 = 'blueoak-1.0.0',
  BSD2ClausePlusPatentLicense = 'bsd-2-clause-patent',
  BSD2ClauseSimplifiedLicense = 'bsd-2-clause',
  BSD3ClauseClearLicense = 'bsd-3-clause-clear',
  BSD3ClauseNeworRevisedLicense = 'bsd-3-clause',
  BSD4ClauseOriginalorOldLicense = 'bsd-4-clause',
  BoostSoftwareLicense1 = 'bsl-1.0',
  CreativeCommonsAttribution4International = 'cc-by-4.0',
  CreativeCommonsAttributionShareAlike4International = 'cc-by-sa-4.0',
  CreativeCommonsZerov1Universal = 'cc0-1.0',
  CeCILLFreeSoftwareLicenseAgreementv2_1 = 'cecill-2.1',
  CERNOpenHardwareLicenceVersion2Permissive = 'cern-ohl-p-2.0',
  CERNOpenHardwareLicenceVersion2StronglyReciprocal = 'cern-ohl-s-2.0',
  CERNOpenHardwareLicenceVersion2WeaklyReciprocal = 'cern-ohl-w-2.0',
  EducationalCommunityLicensev2 = 'ecl-2.0',
  EclipsePublicLicense1 = 'epl-1.0',
  EclipsePublicLicense2 = 'epl-2.0',
  EuropeanUnionPublicLicense1_1 = 'eupl-1.1',
  EuropeanUnionPublicLicense1_2 = 'eupl-1.2',
  GNUFreeDocumentationLicensev1_3 = 'gfdl-1.3',
  GNUGeneralPublicLicensev2 = 'gpl-2.0',
  GNUGeneralPublicLicensev3 = 'gpl-3.0',
  ISCLicense = 'isc',
  GNULesserGeneralPublicLicensev2_1 = 'lgpl-2.1',
  GNULesserGeneralPublicLicensev3 = 'lgpl-3.0',
  LaTeXProjectPublicLicensev1_3c = 'lppl-1.3c',
  MITNoAttribution = 'mit-0',
  MITLicense = 'mit',
  MozillaPublicLicense2 = 'mpl-2.0',
  MicrosoftPublicLicense = 'ms-pl',
  MicrosoftReciprocalLicense = 'ms-rl',
  MulanPermissiveSoftwareLicenseVersion2 = 'mulanpsl-2.0',
  UniversityofIllinoisNCSAOpenSourceLicense = 'ncsa',
  OpenDataCommonsOpenDatabaseLicensev1 = 'odbl-1.0',
  SILOpenFontLicense1_1 = 'ofl-1.1',
  OpenSoftwareLicense3 = 'osl-3.0',
  PostgreSQLLicense = 'postgresql',
  TheUnlicense = 'unlicense',
  UniversalPermissiveLicensev1 = 'upl-1.0',
  VimLicense = 'vim',
  DoWhatTheFYouWantToPublicLicense = 'wtfpl',
  zlibLicense = 'zlib',
  Other = 'other',
}
